# Generated by Django 2.2.6 on 2019-10-19 22:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('phone_home', models.CharField(blank=True, max_length=32, verbose_name='Phone (Home)')),
                ('phone_mobile', models.CharField(blank=True, max_length=32, verbose_name='Phone (Mobile)')),
                ('phone_default', models.CharField(choices=[('home', 'Home'), ('mobi', 'Mobile')], default='home', max_length=4, verbose_name='Default Phone Number')),
                ('elderly', models.BooleanField(blank=True, null=True, verbose_name='Elderly?')),
                ('ambulatory', models.BooleanField(blank=True, null=True, verbose_name='Ambulatory?')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_index', models.IntegerField(default=0, editable=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('destination', models.CharField(blank=True, max_length=256)),
                ('pick_up_time', models.CharField(blank=True, max_length=16)),
                ('appointment_time', models.CharField(blank=True, max_length=16)),
                ('elderly', models.BooleanField(blank=True, null=True, verbose_name='Elderly?')),
                ('ambulatory', models.BooleanField(blank=True, null=True, verbose_name='Ambulatory?')),
                ('note', models.TextField(blank=True, max_length=1024)),
                ('start_miles', models.CharField(blank=True, max_length=32)),
                ('start_time', models.CharField(blank=True, max_length=16)),
                ('end_miles', models.CharField(blank=True, max_length=32)),
                ('end_time', models.CharField(blank=True, max_length=16)),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Canceled')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.Driver')),
                ('trip_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.TripType')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.Vehicle')),
            ],
            options={
                'ordering': ['-date', 'sort_index'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_miles', models.CharField(blank=True, max_length=32)),
                ('start_time', models.CharField(blank=True, max_length=16)),
                ('end_miles', models.CharField(blank=True, max_length=32)),
                ('end_time', models.CharField(blank=True, max_length=16)),
                ('fuel', models.CharField(blank=True, max_length=16, verbose_name='Fuel (gallons)')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.Driver')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.Vehicle')),
            ],
        ),
    ]
