# Generated by Django 2.2.6 on 2019-10-19 23:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['sort_index']},
        ),
        migrations.AddField(
            model_name='driver',
            name='sort_index',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
