# Generated by Django 2.2.6 on 2019-10-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_auto_20191019_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
