# Generated by Django 2.2.6 on 2019-10-19 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0003_auto_20191019_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
