# Generated by Django 2.2.6 on 2019-10-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0006_auto_20191019_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='show_in_shifts',
            field=models.BooleanField(default=True),
        ),
    ]
