# Generated by Django 2.2.6 on 2019-10-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0007_driver_show_in_shifts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='show_in_shifts',
            new_name='is_logged',
        ),
    ]
