# Generated by Django 2.2.6 on 2019-10-26 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0011_vehicleissue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleissue',
            old_name='resolved',
            new_name='is_resolved',
        ),
    ]
