# Generated by Django 2.2.6 on 2019-11-04 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0013_auto_20191026_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_index', models.IntegerField(default=0, editable=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vehicleissue',
            options={'ordering': ['is_resolved', '-priority', '-date']},
        ),
        migrations.CreateModel(
            name='TemplateTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_index', models.IntegerField(default=0, editable=False)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('destination', models.CharField(blank=True, max_length=256)),
                ('pick_up_time', models.CharField(blank=True, max_length=16)),
                ('appointment_time', models.CharField(blank=True, max_length=16)),
                ('elderly', models.BooleanField(blank=True, null=True, verbose_name='Elderly?')),
                ('ambulatory', models.BooleanField(blank=True, null=True, verbose_name='Ambulatory?')),
                ('note', models.TextField(blank=True, max_length=1024)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.Template')),
                ('trip_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.TripType')),
            ],
            options={
                'ordering': ['sort_index'],
            },
        ),
    ]
