# Generated by Django 2.2.6 on 2019-11-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0015_auto_20191106_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatetrip',
            options={'ordering': ['parent', 'sort_index']},
        ),
    ]
