# Generated by Django 2.2.6 on 2019-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0017_schedulemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_home',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone (Home)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone (Mobile)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='schedulemessage',
            name='message',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_miles',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='shift',
            name='fuel',
            field=models.CharField(blank=True, max_length=4, verbose_name='Fuel (gallons)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_miles',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='templatetrip',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='templatetrip',
            name='appointment_time',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='templatetrip',
            name='destination',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='templatetrip',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='templatetrip',
            name='note',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='templatetrip',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='templatetrip',
            name='pick_up_time',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='trip',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='trip',
            name='appointment_time',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_miles',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='trip',
            name='note',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='trip',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pick_up_time',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_miles',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='triptype',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='vehicleissue',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
