# Generated by Django 2.2.6 on 2019-11-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0018_auto_20191108_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='triptype',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
