# Generated by Django 2.2.6 on 2019-11-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0020_auto_20191108_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='phone',
            new_name='phone_home',
        ),
    ]
