# Generated by Django 2.2.6 on 2019-11-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0021_auto_20191110_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='phone_cell',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
