# Generated by Django 2.2.6 on 2019-11-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0022_trip_phone_cell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatetrip',
            old_name='phone',
            new_name='phone_home',
        ),
    ]
