# Generated by Django 2.2.6 on 2019-11-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0025_auto_20191110_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone_mobile',
            new_name='phone_cell',
        ),
    ]
