# Generated by Django 2.2.6 on 2019-11-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0027_auto_20191110_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='is_canceled',
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.IntegerField(choices=[(0, '---------'), (1, 'Canceled'), (2, 'No Show')], default=0),
        ),
    ]
