# Generated by Django 2.2.6 on 2019-11-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0028_auto_20191110_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='color',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
