# Generated by Django 2.2.6 on 2019-11-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0029_auto_20191110_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tags',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
