# Generated by Django 2.2.6 on 2019-11-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0030_trip_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetrip',
            name='tags',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
