# Generated by Django 2.2.6 on 2019-11-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0031_templatetrip_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
