# Generated by Django 2.2.6 on 2019-11-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0033_auto_20191113_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecentTag',
            new_name='FrequentTag',
        ),
        migrations.AlterModelOptions(
            name='frequenttag',
            options={'ordering': ['-count']},
        ),
    ]
