# Generated by Django 2.2.6 on 2019-11-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0034_auto_20191113_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
