# Generated by Django 2.2.6 on 2019-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0035_client_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_activity',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
