# Generated by Django 2.2.6 on 2019-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0036_trip_is_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='donated_cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='donated_check',
            field=models.IntegerField(default=0),
        ),
    ]
