# Generated by Django 2.2.6 on 2019-11-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0038_auto_20191118_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='oil_change_miles',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
