# Generated by Django 2.2.6 on 2019-11-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0039_auto_20191119_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_id', models.UUIDField(editable=False)),
                ('cl_fluids', models.IntegerField(default=0)),
                ('cl_engine', models.IntegerField(default=0)),
                ('cl_headlights', models.IntegerField(default=0)),
                ('cl_hazards', models.IntegerField(default=0)),
                ('cl_directional', models.IntegerField(default=0)),
                ('cl_markers', models.IntegerField(default=0)),
                ('cl_windshield', models.IntegerField(default=0)),
                ('cl_glass', models.IntegerField(default=0)),
                ('cl_mirrors', models.IntegerField(default=0)),
                ('cl_doors', models.IntegerField(default=0)),
                ('cl_tires', models.IntegerField(default=0)),
                ('cl_leaks', models.IntegerField(default=0)),
                ('cl_body', models.IntegerField(default=0)),
                ('cl_registration', models.IntegerField(default=0)),
                ('cl_wheelchair', models.IntegerField(default=0)),
                ('cl_mechanical', models.IntegerField(default=0)),
                ('cl_interior', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.Driver')),
                ('vehicle', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.Vehicle')),
            ],
        ),
    ]
