# Generated by Django 2.2.6 on 2019-11-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0041_auto_20191121_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretrip',
            name='date',
            field=models.DateField(editable=False),
        ),
    ]
