# Generated by Django 2.2.6 on 2019-11-26 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0042_auto_20191125_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleissue',
            name='pretrip',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.PreTrip'),
        ),
        migrations.AddField(
            model_name='vehicleissue',
            name='pretrip_field',
            field=models.CharField(default=False, editable=False, max_length=64),
        ),
    ]
