# Generated by Django 3.0 on 2019-12-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0044_templatetrip_is_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='phone_destination',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone (Destination)'),
        ),
    ]
