# Generated by Django 3.0 on 2019-12-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0046_trip_phone_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetrip',
            name='phone_address',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone (Address)'),
        ),
        migrations.AddField(
            model_name='templatetrip',
            name='phone_destination',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone (Destination)'),
        ),
    ]
