# Generated by Django 3.0 on 2019-12-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0047_auto_20191220_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_quick_edit', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
