# Generated by Django 3.0 on 2020-01-08 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0048_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('body', models.CharField(blank=True, max_length=8192)),
            ],
        ),
    ]
