# Generated by Django 3.0 on 2020-01-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0050_auto_20200108_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='helppage',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='slug',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
