# Generated by Django 3.0 on 2020-01-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0051_auto_20200108_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helppage',
            options={'ordering': ['sort_index']},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='activity_color',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cancel_color',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
