# Generated by Django 3.0 on 2020-01-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0052_auto_20200112_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='activity_color',
            field=models.CharField(blank=True, default='DDD9C3', max_length=8),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cancel_color',
            field=models.CharField(blank=True, default='BBBBBB', max_length=8),
        ),
    ]
