# Generated by Django 3.0 on 2020-01-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0053_auto_20200112_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_quick_edit',
        ),
    ]
