# Generated by Django 3.0 on 2020-01-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0054_remove_sitesettings_enable_quick_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='autocomplete_history_days',
            field=models.IntegerField(default=30),
        ),
    ]
