# Generated by Django 3.0 on 2020-01-16 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0055_sitesettings_autocomplete_history_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ['address'],
            },
        ),
    ]
