# Generated by Django 3.0 on 2020-01-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0056_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='address',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
