# Generated by Django 3.0 on 2020-01-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0057_auto_20200116_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='address',
            field=models.CharField(max_length=128),
        ),
    ]
