# Generated by Django 3.0 on 2020-01-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0058_auto_20200116_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='note',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
