# Generated by Django 3.0 on 2020-02-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0059_shift_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleissue',
            name='category',
            field=models.IntegerField(choices=[(0, '---------'), (1, 'Fuel & Fluids'), (2, 'Engine'), (3, 'Headlights / High Beams'), (4, 'Hazards / Ambers'), (5, 'Directional'), (6, 'Markers / Reflectors'), (7, 'Windshield'), (8, 'Other Glass'), (9, 'Mirrors'), (10, 'Doors'), (11, 'Tires'), (12, 'Leaks'), (13, 'Body Damage'), (14, 'Registration'), (15, 'Wheelchair Lift'), (16, 'Mechanical'), (17, 'Interior')], default=0),
        ),
    ]
