# Generated by Django 3.0 on 2020-02-06 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0060_vehicleissue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetrip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.Driver'),
        ),
        migrations.AddField(
            model_name='templatetrip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.Vehicle'),
        ),
    ]
