# Generated by Django 3.0 on 2020-02-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0061_auto_20200206_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='reset_filter_on_shift_change',
            field=models.BooleanField(default=False, verbose_name='Reset Schedule filter when starting/ending Shift'),
        ),
    ]
