# Generated by Django 3.0 on 2020-02-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0062_sitesettings_reset_filter_on_shift_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='skip_weekends',
            field=models.BooleanField(default=False, verbose_name='Skip weekends in Schedule date picker'),
        ),
    ]
