# Generated by Django 3.0 on 2020-03-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0064_delete_helppage'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetrip',
            name='status',
            field=models.IntegerField(choices=[(0, '---------'), (1, 'Canceled')], default=0),
        ),
    ]
