# Generated by Django 3.0 on 2020-08-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0066_trip_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetrip',
            name='fare',
            field=models.IntegerField(default=0),
        ),
    ]
