# Generated by Django 3.0 on 2020-08-08 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0067_templatetrip_fare'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_paid', models.DateField()),
                ('cash', models.IntegerField(default=0)),
                ('check', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.Client')),
            ],
            options={
                'ordering': ['date_paid'],
            },
        ),
    ]
