# Generated by Django 3.1 on 2020-09-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0068_clientpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Is staff member?'),
        ),
    ]
