# Generated by Django 3.1.1 on 2020-09-16 23:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0069_client_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_index', models.IntegerField(default=0, editable=False)),
                ('name', models.CharField(max_length=128)),
                ('fare', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_index'],
            },
        ),
    ]
