# Generated by Django 3.1.1 on 2020-10-08 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0070_fare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_index', models.IntegerField(default=0, editable=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['sort_index'],
            },
        ),
    ]
