# Generated by Django 3.1.1 on 2020-10-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0071_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrequentTag',
        ),
    ]
