# Generated by Django 3.1.1 on 2020-11-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0072_delete_frequenttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='passenger',
            field=models.BooleanField(default=True, verbose_name='Passenger on vehicle?'),
        ),
    ]
