# Generated by Django 3.1.1 on 2020-11-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0073_trip_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetrip',
            name='passenger',
            field=models.BooleanField(default=True, verbose_name='Passenger on vehicle?'),
        ),
    ]
