# Generated by Django 3.1.4 on 2021-02-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0076_auto_20210206_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='page_title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='short_page_title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
