# Generated by Django 3.2 on 2021-04-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0077_auto_20210220_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='color',
            field=models.CharField(blank=True, default='FFFFFF', max_length=8),
        ),
        migrations.AlterField(
            model_name='loggedevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
