# Generated by Django 3.2 on 2021-04-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0079_destination_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
