# Generated by Django 3.2 on 2021-08-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0080_client_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptype',
            name='is_trip_counted',
            field=models.BooleanField(default=True, verbose_name='Included in report trip counts?'),
        ),
    ]
