# Generated by Django 3.2 on 2021-10-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0081_triptype_is_trip_counted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='no_show_color',
            field=models.CharField(blank=True, default='888888', max_length=8),
        ),
    ]
