# Generated by Django 4.0 on 2021-12-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0082_sitesettings_no_show_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientpayment',
            old_name='cash',
            new_name='money_cash',
        ),
        migrations.RenameField(
            model_name='clientpayment',
            old_name='check',
            new_name='money_check',
        ),
    ]
