# Generated by Django 3.2.10 on 2021-12-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0083_rename_cash_clientpayment_money_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pretrip_warning_threshold',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='pretrip',
            name='shift_id',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
