# Generated by Django 3.2.10 on 2022-07-11 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0086_trip_cancel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_index', models.IntegerField(default=0, editable=False)),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, default='FFFFFF', max_length=8)),
            ],
            options={
                'ordering': ['sort_index'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='activity_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.activitycolor'),
        ),
    ]
