# Generated by Django 3.2.10 on 2022-08-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0087_auto_20220711_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetrip',
            name='format',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='format',
            field=models.IntegerField(default=0),
        ),
    ]
