# Generated by Django 3.2.10 on 2022-08-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0089_data_trip_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatetrip',
            name='is_activity',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='is_activity',
        ),
        migrations.AlterField(
            model_name='templatetrip',
            name='format',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='format',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
