# Generated by Django 3.2.10 on 2022-08-03 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0091_data_clean_client_update_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetrip',
            name='activity_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit.activitycolor'),
        ),
    ]
