# Generated by Django 3.2.10 on 2022-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0092_templatetrip_activity_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone (Alternate)'),
        ),
        migrations.AddField(
            model_name='templatetrip',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone (Alternate)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone (Alternate)'),
        ),
    ]
