# Generated by Django 3.2.10 on 2022-10-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0093_auto_20220929_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_transit_policy_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
