# Generated by Django 3.2.10 on 2023-09-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0100_auto_20230330_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='additional_pickup_fuzziness',
            field=models.FloatField(default=0.6),
        ),
    ]
