# Generated by Django 3.2.10 on 2023-10-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0101_sitesettings_additional_pickup_fuzziness'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='simple_daily_logs',
            field=models.BooleanField(default=False, verbose_name='Simple daily logs'),
        ),
    ]
