# Generated by Django 3.2.10 on 2024-01-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0102_sitesettings_simple_daily_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='simple_daily_logs',
            field=models.BooleanField(default=False),
        ),
    ]
