# Generated by Django 3.2.10 on 2024-01-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0104_trip_cancel_date_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='trip_cancel_late_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
