# Generated by Django 3.2.10 on 2024-03-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0106_vehicle_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_shown_in_notifications',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notif_level',
            field=models.IntegerField(choices=[(0, 'All'), (1, 'Maintainence Only'), (2, 'None')], default=0),
        ),
    ]
