# Generated by Django 4.2.11 on 2025-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0108_driver_default_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='flag',
            field=models.IntegerField(choices=[(0, '---------'), (1, 'Wheelchair')], default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='style',
            field=models.IntegerField(choices=[(0, '---------'), (1, 'Important')], default=0),
        ),
    ]
