# Generated by Django 4.2.11 on 2025-05-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0109_tag_flag_tag_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trip_creation_notes',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='style',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Important')], default=0),
        ),
    ]
