# Generated by Django 4.2.11 on 2025-06-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0110_client_trip_creation_notes_alter_tag_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
