# Generated by Django 4.2.11 on 2025-08-06 18:25

from django.db import migrations, models

def set_inspect_type(apps, schema_editor):
    PreTrip = apps.get_model('transit', 'PreTrip')

    # inspect_type defaults to 0 (TYPE_PRE), so we only need to set TYPE_NO_SHIFT where it applies
    for pretrip in PreTrip.objects.filter(shift_id=None):
        pretrip.inspect_type = 2 # PreTrip.TYPE_NO_SHIFT
        pretrip.save()

class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0111_vehicle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretrip',
            name='inspect_type',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_inspect_type)
    ]
