# Generated by Django 4.2.11 on 2025-08-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0112_pretrip_inspect_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDeltaTimeAverage',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('avg_time', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
