# Generated by Django 4.2.11 on 2025-09-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0113_tripdeltatimeaverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='trip_eta_buffer',
            field=models.IntegerField(default=0),
        ),
    ]
