# Generated by Django 4.2.11 on 2025-09-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0114_sitesettings_trip_eta_buffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-date', 'sort_index']},
        ),
        migrations.AddField(
            model_name='shift',
            name='sort_index',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
