# Generated by Django 4.2.11 on 2025-09-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0116_update_shift_sort_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='cancel_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.IntegerField(choices=[(0, '---------'), (1, 'Canceled')], default=0),
        ),
    ]
