# Generated by Django 4.2.11 on 2025-10-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0117_shift_cancel_date_shift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='usage_style',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Field Trips')], default=0),
        ),
    ]
