# Generated by Django 4.2.11 on 2025-11-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0118_client_usage_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleissue',
            name='resolution_notes',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
