# Generated by Django 4.2.11 on 2025-11-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0119_vehicleissue_resolution_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleissue',
            name='is_resolved',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Resolved'), (2, 'Triaged / Known Issue')], default=0),
        ),
    ]
