# Generated by Django 4.2.11 on 2025-11-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0120_alter_vehicleissue_is_resolved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleissue',
            options={'ordering': ['status', '-priority', '-date']},
        ),
        migrations.RenameField(
            model_name='vehicleissue',
            old_name='is_resolved',
            new_name='status',
        ),
    ]
