# Generated by Django 4.2.11 on 2025-12-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0121_alter_vehicleissue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='maintainence_notes',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
