# Generated by Django 4.2.11 on 2025-12-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0122_vehicle_maintainence_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='maintainence_notes',
            new_name='maintainance_notes',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notif_level',
            field=models.IntegerField(choices=[(0, 'All'), (1, 'Maintainance Only'), (2, 'None')], default=0),
        ),
    ]
