# Generated by Django 4.2.11 on 2025-12-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0123_rename_maintainence_notes_vehicle_maintainance_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretrip',
            name='cl_post_exterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pretrip',
            name='cl_post_interior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pretrip',
            name='cl_post_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicleissue',
            name='category',
            field=models.IntegerField(choices=[(0, '---------'), (1, 'Fuel & Fluids'), (2, 'Engine'), (3, 'Headlights / High Beams'), (4, 'Hazards / Ambers'), (5, 'Directional'), (6, 'Markers / Reflectors'), (7, 'Windshield'), (8, 'Other Glass'), (9, 'Mirrors'), (10, 'Doors'), (11, 'Tires'), (12, 'Leaks'), (13, 'Body Damage'), (14, 'Registration'), (15, 'Wheelchair Lift'), (16, 'Mechanical'), (17, 'Interior'), (18, 'Exterior')], default=0),
        ),
    ]
