# Generated by Django 4.2.11 on 2026-03-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0125_update_posttrip_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='notes',
            field=models.CharField(default='', max_length=128),
        ),
    ]
