# Generated by Django 4.2.11 on 2026-05-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0126_volunteer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='wheelchair_lift_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
