# Generated by Django 2.2.6 on 2019-10-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('pick_up_time', models.DateTimeField(blank=True)),
                ('appointment_time', models.DateTimeField(blank=True)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('destination', models.CharField(blank=True, max_length=256)),
                ('start_miles', models.CharField(blank=True, max_length=32)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_miles', models.CharField(blank=True, max_length=32)),
                ('end_time', models.DateTimeField(blank=True)),
                ('note', models.CharField(blank=True, max_length=1024)),
                ('client_elderly', models.BooleanField(blank=True, null=True)),
                ('client_ambulatory', models.BooleanField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Driver')),
                ('trip_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.TripType')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Vehicle')),
            ],
        ),
    ]
