# Generated by Django 2.2.6 on 2019-10-09 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-trip_date']},
        ),
    ]
