# Generated by Django 2.2.6 on 2019-10-09 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191008_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={},
        ),
    ]
