# Generated by Django 2.2.6 on 2019-10-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191008_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pick_up_time',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
