# Generated by Django 2.2.6 on 2019-10-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20191008_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='client_ambulatory',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ambulatory?'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='client_elderly',
            field=models.BooleanField(blank=True, null=True, verbose_name='Elderly?'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='note',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
