# Generated by Django 2.2.6 on 2019-10-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20191009_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_miles', models.CharField(blank=True, max_length=32)),
                ('start_time', models.CharField(blank=True, max_length=16)),
                ('end_miles', models.CharField(blank=True, max_length=32)),
                ('end_time', models.CharField(blank=True, max_length=16)),
                ('fuel', models.CharField(blank=True, max_length=16)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Driver')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Vehicle')),
            ],
        ),
    ]
