# Generated by Django 2.2.6 on 2019-10-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ambulatory',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ambulatory?'),
        ),
        migrations.AddField(
            model_name='client',
            name='elderly',
            field=models.BooleanField(blank=True, null=True, verbose_name='Elderly?'),
        ),
    ]
