# Generated by Django 2.2.6 on 2019-10-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20191013_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='trip',
            name='sort_index',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
