# Generated by Django 2.2.6 on 2019-10-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20191013_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date', 'sort_index']},
        ),
    ]
