# Generated by Django 2.2.6 on 2019-10-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20191013_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='fuel',
            field=models.CharField(blank=True, max_length=16, verbose_name='Fuel (gallons)'),
        ),
    ]
