# Generated by Django 2.2.6 on 2019-10-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_auto_20191016_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_home',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
