# Generated by Django 2.2.6 on 2019-10-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20191016_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone (Mobile'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_home',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone (Home)'),
        ),
    ]
