# Generated by Django 2.2.6 on 2019-10-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20191018_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_default',
            field=models.CharField(choices=[('home', 'Home'), ('mobi', 'Mobile')], default='home', max_length=4, verbose_name='Default Phone Number'),
        ),
    ]
