# Generated by Django 2.2.6 on 2019-10-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_client_phone_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone (Mobile)'),
        ),
    ]
